### Ignore Warning Messages from Python

In [1]:
import warnings
warnings.filterwarnings('ignore')

### Importing Libraries

In [2]:
import pandas as pd

### Read in two CSV files

In [3]:
df1 = pd.read_csv('../data/imputed_data.csv', sep=',')

In [4]:
df2 = pd.read_csv('../data/US_counties_COVID19_health_weather_data.csv', sep=',')

In [5]:
df1.head(2)

,cases,deaths,total_population,population_density_per_sqmi,num_deaths,percent_fair_or_poor_health,average_number_of_physically_unhealthy_days,average_number_of_mentally_unhealthy_days,percent_low_birthweight,percent_smokers,...,wind_speed,max_wind_speed,wind_gust,precipitation,fog,rain,snow,hail,thunder,tornado
0,1.0,0.0,758649.0,363.586159,7592.0,14.403971,3.700802,3.700968,6.047001,12.962309,...,8.3,19.0,28.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0
1,1.0,0.0,758649.0,363.586159,7592.0,14.403971,3.700802,3.700968,6.047001,12.962309,...,13.2,21.0,26.0,0.29,0.0,1.0,0.0,0.0,0.0,0.0

In [6]:
df2.head(2)

,date,county,state,fips,cases,deaths,stay_at_home_announced,stay_at_home_effective,lat,lon,...,min_temp_3d_avg,min_temp_5d_avg,min_temp_10d_avg,min_temp_15d_avg,dewpoint_3d_avg,dewpoint_5d_avg,dewpoint_10d_avg,dewpoint_15d_avg,date_stay_at_home_announced,date_stay_at_home_effective
0,2020-01-21,Snohomish,Washington,53061,1,0.0,no,no,48.047489,-121.697307,...,38.266667,38.92,38.44,36.146667,40.333333,41.64,40.74,37.973333,2020-03-23,2020-03-23
1,2020-01-22,Snohomish,Washington,53061,1,0.0,no,no,48.047489,-121.697307,...,39.233333,41.12,39.76,37.613333,42.633333,42.98,41.68,39.440000,2020-03-23,2020-03-23

### Drop nulls from 'deaths' in df2

In [7]:
df2_dropped = df2[df2['deaths'].notna()]

In [8]:
df2_dropped.shape

(773676, 227)

### Drop not needed columns

In [9]:
def clean_cols(data):
    for i in data:
        if (i=='date' or i=='county' or i=='state'):
            continue
        else:
            data = data.drop(i, axis=1)
    return data

df3 = clean_cols(df2_dropped)

In [10]:
df3.head(2)

         date     county       state
0  2020-01-21  Snohomish  Washington
1  2020-01-22  Snohomish  Washington

### Check to see if shapes match

In [11]:
df3.shape

(773676, 3)

In [12]:
df1.shape

(773676, 194)

### Concatenate the two dataframes

In [13]:
result = pd.concat([df3.reset_index(drop=True), df1.reset_index(drop=True)], axis=1)

In [14]:
result

,date,county,state,cases,deaths,total_population,population_density_per_sqmi,num_deaths,percent_fair_or_poor_health,average_number_of_physically_unhealthy_days,...,wind_speed,max_wind_speed,wind_gust,precipitation,fog,rain,snow,hail,thunder,tornado
0,2020-01-21,Snohomish,Washington,1.0,0.0,758649.0,363.586159,7592.0,14.403971,3.700802,...,8.30,19.00,28.00,0.00,0.0,1.0,0.0,0.0,0.0,0.0
1,2020-01-22,Snohomish,Washington,1.0,0.0,758649.0,363.586159,7592.0,14.403971,3.700802,...,13.20,21.00,26.00,0.29,0.0,1.0,0.0,0.0,0.0,0.0
2,2020-01-23,Snohomish,Washington,1.0,0.0,758649.0,363.586159,7592.0,14.403971,3.700802,...,12.00,20.00,26.00,0.54,0.0,1.0,0.0,0.0,0.0,0.0
3,2020-01-24,Cook,Illinois,1.0,0.0,5227575.0,5531.878539,57660.0,17.140851,3.471088,...,4.80,9.90,22.62,0.16,1.0,1.0,1.0,0.0,0.0,0.0
4,2020-01-24,Snohomish,Washington,1.0,0.0,758649.0,363.586159,7592.0,14.403971,3.700802,...,13.00,22.00,28.00,0.32,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
773671,2020-12-04,Sweetwater,Wyoming,2077.0,10.0,44812.0,4.297803,532.0,14.813082,3.402029,...,5.20,7.00,27.20,0.00,0.0,0.0,0.0,0.0,0.0,0.0
773672,2020-12-04,Teton,Wyoming,1724.0,2.0,22623.0,5.661502,109.0,11.914358,3.031233,...,4.90,9.80,17.96,0.00,0.0,0.0,0.0,0.0,0.0,0.0
773673,2020-12-04,Uinta,Wyoming,1175.0,5.0,20893.0,10.035892,256.0,15.537464,3.628488,...,3.70,8.90,22.82,0.00,0.0,0.0,0.0,0.0,0.0,0.0
773674,2020-12-04,Washakie,Wyoming,517.0,8.0,8351.0,3.730539,110.0,15.955971,3.613308,...,1.70,4.10,27.86,0.00,0.0,0.0,0.0,0.0,0.0,0.0
773675,2020-12-04,Weston,Wyoming,419.0,2.0,7175.0,2.991964,89.0,13.934025,3.463619,...,7.96,16.38,22.82,0.00,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
result.shape

(773676, 197)

### Save as csv

In [16]:
result.to_csv('../data/tableau_data.csv', sep=',', index=False)

### Check if csv has any unwanted data after converting to csv

In [17]:
test_result = pd.read_csv('../data/tableau_data.csv', sep=',')

In [18]:
test_result

,date,county,state,cases,deaths,total_population,population_density_per_sqmi,num_deaths,percent_fair_or_poor_health,average_number_of_physically_unhealthy_days,...,wind_speed,max_wind_speed,wind_gust,precipitation,fog,rain,snow,hail,thunder,tornado
0,2020-01-21,Snohomish,Washington,1.0,0.0,758649.0,363.586159,7592.0,14.403971,3.700802,...,8.30,19.00,28.00,0.00,0.0,1.0,0.0,0.0,0.0,0.0
1,2020-01-22,Snohomish,Washington,1.0,0.0,758649.0,363.586159,7592.0,14.403971,3.700802,...,13.20,21.00,26.00,0.29,0.0,1.0,0.0,0.0,0.0,0.0
2,2020-01-23,Snohomish,Washington,1.0,0.0,758649.0,363.586159,7592.0,14.403971,3.700802,...,12.00,20.00,26.00,0.54,0.0,1.0,0.0,0.0,0.0,0.0
3,2020-01-24,Cook,Illinois,1.0,0.0,5227575.0,5531.878539,57660.0,17.140851,3.471088,...,4.80,9.90,22.62,0.16,1.0,1.0,1.0,0.0,0.0,0.0
4,2020-01-24,Snohomish,Washington,1.0,0.0,758649.0,363.586159,7592.0,14.403971,3.700802,...,13.00,22.00,28.00,0.32,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
773671,2020-12-04,Sweetwater,Wyoming,2077.0,10.0,44812.0,4.297803,532.0,14.813082,3.402029,...,5.20,7.00,27.20,0.00,0.0,0.0,0.0,0.0,0.0,0.0
773672,2020-12-04,Teton,Wyoming,1724.0,2.0,22623.0,5.661502,109.0,11.914358,3.031233,...,4.90,9.80,17.96,0.00,0.0,0.0,0.0,0.0,0.0,0.0
773673,2020-12-04,Uinta,Wyoming,1175.0,5.0,20893.0,10.035892,256.0,15.537464,3.628488,...,3.70,8.90,22.82,0.00,0.0,0.0,0.0,0.0,0.0,0.0
773674,2020-12-04,Washakie,Wyoming,517.0,8.0,8351.0,3.730539,110.0,15.955971,3.613308,...,1.70,4.10,27.86,0.00,0.0,0.0,0.0,0.0,0.0,0.0
773675,2020-12-04,Weston,Wyoming,419.0,2.0,7175.0,2.991964,89.0,13.934025,3.463619,...,7.96,16.38,22.82,0.00,0.0,0.0,0.0,0.0,0.0,0.0